server:
  port: 8081
spring:
  application:
    name: xmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.26.37.73:3306/xmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 120.26.37.73
    port: 6379
    database: 0
    password: aliredis123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.xmdp.entity # 别名扫描包
logging:
  level:
    com.xmdp: debug